version: '3.7'
services:

  mongo:
    image: 'mongo:latest'
    restart: always
    container_name: mongo
    volumes:
      - /Users/qiqiang/Desktop/docker-supershop/docker-compose/mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - ipoemnet

  back:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    container_name: back
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    ports:
      - 8111:8111
    depends_on:
      - mongo
    networks:
      - ipoemnet

  h5:
    build:
      context: .
      dockerfile: ./Dockerfile-h5
    restart: always
    container_name: h5
    ports:
      - 7071:7071
    networks:
      - ipoemnet

networks:
  ipoemnet:
    driver: bridge
    name: ipoemnet
