spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chinese_poetry?serverTimezone=GMT&useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: mypassword
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info,health
server:
  port: 8111
poetry:
  es:
    index: chinese_poetry_shi_new
    address: mycloud:9200